### ISSUE TITLE
Error with ios_template.py

### ISSUE THREAD

**Issue by quanhua92** [trongdth/xcode_template#1]
xcode_template git:(master) ✗ python ios_template.py -d /Users/quanhua92/workspace/xcode_template/Sample/Base.xctemplate/
Traceback (most recent call last):
  File "ios_template.py", line 57, in <module>
    main(sys.argv[1:])
  File "ios_template.py", line 53, in main
    copy_template(path_to_template)
  File "ios_template.py", line 32, in copy_template
    go_to_template_folder(**xcode6_project_template_path)
  File "ios_template.py", line 22, in go_to_template_folder
    print __ERR2** + " " + e
TypeError: cannot concatenate 'str' and 'exceptions.OSError' objects

**Comment by trongdth** [comment]
It has been fixed
